const { gql } = require('apollo-server');

const typeDefs = gql`  
  type Player {
    id: ID!,
    name: String!,
    full_name: String!,
    birth_date: String!,
    age: Int!,
    height_cm: Float!,
    weight_kgs: Float!,
    positions: String!,
    nationality: String!,
    overall_rating: Int!,
    potential: Int!,
    value_euro: String, # data should be numerical but it is not clean at the moment
    wage_euro: String, # data should be numerical but it is not clean at the moment
    preferred_foot: String!,
    international_reputation: Int,
    weak_foot: Int!,
    skill_moves: Int!,
    work_rate: String,
    body_type: String,
    release_clause_euro: Float,
    club_team: String,
    club_rating: Int,
    club_position: String,
    club_jersey_number: Int,
    club_join_date: String,
    contract_end_year: String,
    national_team: String
    national_rating: Int,
    national_team_position: String,
    national_jersey_number: Int,
    crossing: Int,
    finishing: Int,
    heading_accuracy: Int,
    short_passing: Int,
    volleys: Int,
    dribbling: Int,
    curve: Int,
    freekick_accuracy: Int,
    long_passing: Int,
    ball_control: Int,
    acceleration: Int,
    sprint_speed: Int,
    agility: Int,
    reactions: Int,
    balance: Int,
    shot_power: Int,
    jumping: Int,
    stamina: Int,
    strength: Int,
    long_shots: Int,
    aggression: Int,
    interceptions: Int,
    positioning: Int,
    vision: Int,
    penalties: Int,
    composure: Int,
    marking: Int,
    standing_tackle: Int,
    sliding_tackle: Int,
    GK_diving: Int,
    GK_handling: Int,
    GK_kicking: Int,
    GK_positioning: Int,
    GK_reflexes: Int,
    tags: String,
    traits: String,
    LS: String,
    ST: String,
    RS: String,
    LW: String,
    LF: String,
    CF: String,
    RF: String,
    RW: String,
    LAM: String,
    CAM: String,
    RAM: String,
    LM: String,
    LCM: String,
    CM: String,
    RCM: String,
    RM: String,
    LWB: String,
    LDM: String,
    CDM: String,
    RDM: String,
    RWB: String,
    LB: String,
    LCB: String,
    CB: String,
    RCB: String,
    RB: String
  }
  
  type Query {
    players: [Player]
    player(id: String): Player
  }
`;

module.exports = typeDefs;